### ISSUE TITLE
Telluric wavelength calibration error

### ISSUE THREAD

**Issue by wei-lingfeng** [chihchunhsu/smart#10]
`TypeError: convolveTelluric() missing 2 required positional arguments: 'pwv' and 'telluric_data'`
When executing:
https://github.com/chihchunhsu/smart/blob/7e2416b190fff59dea8538486df07c0ff8254f90/smart/forward_model/model_fit.py#L714

The function is defined here:
https://github.com/chihchunhsu/smart/blob/7e2416b190fff59dea8538486df07c0ff8254f90/smart/forward_model/tellurics.py#L130

**Comment by chihchunhsu** [comment]
I changed the version back for this function; I defined this function in two places
