### ISSUE TITLE
Missing parameter 'order'

### ISSUE THREAD

**Issue by wei-lingfeng** [chihchunhsu/smart#17]
The function smart.Model misses a parameter 'order'. It's looking for a directory 'APOGEE-NONE' due to the unspecified order, while it should be looking for 'APOGEE-ALL'.
https://github.com/chihchunhsu/smart/blob/9ca3646c4a5c94b8aac4c4fb2791c70fbd64aeba/smart/forward_model/model_fit.py#L90

**Comment by chihchunhsu** [comment]
I have never updated this function for APOGEE for a while; updated it now

**Comment by chihchunhsu** [comment]
My code below to run the makeModel function for APOGEE:

```
model        = smart.makeModel(teff=teff, logg=logg, metal=metal, rv=rv, vsini=vsini,
                               airmass=am, pwv=pwv, 
                               wave_off1=wave_off1, wave_off2=wave_off2, wave_off3=wave_off3,
                               c0_1=c0_1, c1_1=c1_1, c2_1=c2_1, 
                               modelset=modelset, instrument=instrument, order='ALL', data=data,
                               lsf=lsf, xlsf=xlsf)
```

**Comment by wei-lingfeng** [comment]
Thank you!
