### ISSUE TITLE
New version of numpy doesn't use np.int

### ISSUE THREAD

**Issue by ctheissen** [chihchunhsu/smart#19]
Need to fix this throughout probably.

```
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
```

**Comment by chihchunhsu** [comment]
What version of numpy are you using? Numpy has several backward-incompatible things that they changed but I haven't seen much benefits of using newer versions of numpy

**Comment by ctheissen** [comment]
1.24.2.
We might need to think about some sort of version check.

**Comment by chihchunhsu** [comment]
I am using 1.21.6. Honesty I mostly stick with Python 3.7 for developing SMART since there were too much (unncessary) pain to deal with incompatible software upgrades.

Almost sure your errors come from the wavelength calibration width computation. A simply fix is just to change np.int into int.

**Comment by chihchunhsu** [comment]
Just made the change; give it a try to see if that works on your environment!

**Comment by chihchunhsu** [comment]
Should be good now
