### ISSUE TITLE
No more "trapz" in scipy.integrate. It's now called "trapezoid".

### ISSUE THREAD

**Issue by ctheissen** [chihchunhsu/smart#25]
It will be an issue for future versions.

**Comment by chihchunhsu** [comment]
Should we handle different versions in this case (e.g. try/except or if/else)? I am still using Python 3.7 and 3.8 for my baseline setup

**Comment by ctheissen** [comment]
I tried to make a cheap fix in the new branch. You can see what I did in #26

**Comment by chihchunhsu** [comment]
Sounds good. We can make a test script there. I am starting to make the first test script for interpolation

**Comment by chihchunhsu** [comment]
Using Chris' implementation to fix this #26
