### ISSUE TITLE
Making the custom mask for telluric calibration a little more intuitive

### ISSUE THREAD

**Issue by ctheissen** [chihchunhsu/smart#3]
If someone is going to apply a custom mask, it shouldn't also apply the cal params in my opinion.
```
elif not applymask:
   data.flux  = np.delete(data.oriFlux, mask_custom)[pixel_range_start: pixel_range_end]
   data.wave  = np.delete(data.oriWave, mask_custom)[pixel_range_start: pixel_range_end]
   data.noise = np.delete(data.oriNoise, mask_custom)[pixel_range_start: pixel_range_end]
```
should be
```
elif not applymask:
   data.flux  = np.delete(data.oriFlux, mask_custom)
   data.wave  = np.delete(data.oriWave, mask_custom)
   data.noise = np.delete(data.oriNoise, mask_custom)
```
Also, it's very confusing that to use a custom mask you need to set applymask=False. That's very counter-intuitive!

**Comment by chihchunhsu** [comment]
I agree with you that we should remove the edge pixels masking from the cal_params, so I just removed them. 

Thanks for pointing the "applymask" keyword out. What "applymask" does is the sigma clipping mask method, so I would suggest if we redefine the keyword as "apply_sigma_mask" or "sigma_mask"?

**Comment by chihchunhsu** [comment]
Changed the "applymask" keyword into "apply_sigma_mask".
