### ISSUE TITLE
Telluric Wavelength Calibration Data Type Issue

### ISSUE THREAD

**Issue by Lingfeng-Wei** [chihchunhsu/smart#4]
https://github.com/chihchunhsu/smart/blob/c4cf0bb173cb0196cb9024b1ee2caeb0eff03e69/smart/wavelength_calibration/telluric_wavelength_fit.py#L617

In this line, if the data.mask is an empty list, numpy.union1d will return a float type list or array. Thus numpy.delete will raise a datatype error.
e.g.:
`np.delete(np.array([0,1,2,3]), np.union1d([], [1,3]))`
will raise an error.

The same goes with:
https://github.com/chihchunhsu/smart/blob/c4cf0bb173cb0196cb9024b1ee2caeb0eff03e69/smart/wavelength_calibration/telluric_wavelength_fit.py#L1355

Maybe add a line
`mask_combined = mask_combined.astype(int)`
or use set union instead
`mask_combined = np.array(list(set(mask_custom).union(set(data.mask))))`

**Comment by chihchunhsu** [comment]
fixed!
