### ISSUE TITLE
Image Type Keyword Issue

### ISSUE THREAD

**Issue by Wei-Lingfeng** [chihchunhsu/smart#8]
It seems NIRSPEC has recently changed the keyword “IMAGETYP” to "IMTYPE". Might need to add a judgment whether "IMTYPE" or "IMAGETYP" is in data.keys().

https://github.com/chihchunhsu/smart/blob/9e22d005d9a1f5c3bc32982ad3f450e77e0d51fd/smart/utils/defringeflat.py#L451-L452

**Comment by chihchunhsu** [comment]
Should be fixed now.
